[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["packages"]
addopts = "--strict-markers"
pythonpath = [
    "packages/dffmpeg-common/src",
    "packages/dffmpeg-coordinator/src",
    "packages/dffmpeg-client/src",
    "packages/dffmpeg-worker/src",
]
markers = [
    "unit: small, fast tests",
    "integration: larger tests involving multiple components",
]
