[project]
name = "dffmpeg-coordinator"
version = "0.1.0"
authors = [
    { name="Bryan Wyatt", email="brwyatt@gmail.com" },
]
description = "Coordinator application components for dffmpeg"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "aiomqtt>=2.5.0, <3.0.0",
    "aio-pika>=9.5.0, <10.0.0",
    "dnspython>=2.6.0, <3.0.0",
    "aiosqlite>=0.22.0, <1.0.0",
    "dffmpeg-common~=0.1.0",
    "fastapi>=0.128.0, <1.0.0",
    "jinja2>=3.1.0, <4.0.0",
    "pydantic>=2.12.0, <3.0.0",
    "python-ulid[pydantic]>=3.1.0, <4.0.0",
    "pyyaml>=6.0.0, <7.0.0",
    "sqlalchemy>=2.0.0, <3.0.0",
    "uvicorn>=0.40.0, <1.0.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dffmpeg.*"]
namespaces = true

[project.optional-dependencies]
test = [
    "anyio>=4.12.0, <5.0.0",
    "black>=26.1.0, <27.0.0",
    "flake8>=7.3.0, <8.0.0",
    "isort>=7.0.0, <8.0.0",
    "pytest>=9.0.0, <10.0.0",
    "pytest-asyncio>=1.3.0, <2.0.0",
]
dev = [
    "dffmpeg-coordinator[test]",
    "httpx>=0.28.0, <1.0.0",
    "ipython>=9.10.0, <10.0.0",
]

[tool.setuptools.package-data]
"*" = ["*.html"]

[project.scripts]
dffmpeg-coordinator = "dffmpeg.coordinator.cli:main"
dffmpeg-admin = "dffmpeg.coordinator.admin_cli:main"

[project.entry-points."dffmpeg.db.auth"]
sqlite = "dffmpeg.coordinator.db.auth.sqlite:SQLiteAuthRepository"

[project.entry-points."dffmpeg.db.jobs"]
sqlite = "dffmpeg.coordinator.db.jobs.sqlite:SQLiteJobRepository"

[project.entry-points."dffmpeg.db.messages"]
sqlite = "dffmpeg.coordinator.db.messages.sqlite:SQLiteMessageRepository"

[project.entry-points."dffmpeg.db.workers"]
sqlite = "dffmpeg.coordinator.db.workers.sqlite:SQLiteWorkerRepository"

[project.entry-points."dffmpeg.transports.server"]
http_polling = "dffmpeg.coordinator.transports.http_polling:HTTPPollingTransport"
mqtt = "dffmpeg.coordinator.transports.mqtt:MQTTServerTransport"
rabbitmq = "dffmpeg.coordinator.transports.rabbitmq:RabbitMQServerTransport"
