[project]
name = "dffmpeg-common"
version = "0.1.0"
authors = [
    { name="Bryan Wyatt", email="brwyatt@gmail.com" },
]
description = "Common library functions for dffmpeg applications"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "cryptography",
    "pydantic>=2.0",
    "python-ulid[pydantic]",
    "pydantic-extra-types[python_ulid]",
]

[project.entry-points."dffmpeg.common.crypto"]
fernet = "dffmpeg.common.crypto.fernet:FernetEncryption"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dffmpeg.*"]
namespaces = true

[project.optional-dependencies]
test = [
    "pytest",
    "black",
    "isort",
    "flake8",
]
dev = [
    "dffmpeg-common[test]",
    "ipython",
]
