[project]
name = "dffmpeg-client"
version = "0.1.0"
authors = [
    { name="Bryan Wyatt", email="brwyatt@gmail.com" },
]
description = "Client application components for dffmpeg"
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]
urls = { Homepage = "https://github.com/brwyatt/dffmpeg", Repository = "https://github.com/brwyatt/dffmpeg" }
dependencies = [
    "dffmpeg-common~=0.1.0",
    "httpx>=0.28.0, <1.0.0",
    "pyyaml>=6.0.0, <7.0.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dffmpeg.*"]
namespaces = true

[project.optional-dependencies]
test = [
    "anyio>=4.12.0, <5.0.0",
    "black>=26.1.0, <27.0.0",
    "flake8>=7.3.0, <8.0.0",
    "isort>=7.0.0, <9.0.0",
    "pytest>=9.0.0, <10.0.0",
    "pytest-asyncio>=1.3.0, <2.0.0",
]
dev = [
    "dffmpeg-client[test]",
    "ipython>=9.10.0, <10.0.0",
]

[project.scripts]
dffmpeg-client = "dffmpeg.client.cli:main"
dffmpeg_proxy = "dffmpeg.client.cli:proxy_main"
