[project]
name = "dffmpeg-worker"
version = "0.1.0"
authors = [
    { name="Bryan Wyatt", email="brwyatt@gmail.com" },
]
description = "Worker application components for dffmpeg"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "dffmpeg-common~=0.1.0",
    "pydantic>=2.12.0, <3.0.0",
    "pyyaml>=6.0.0, <7.0.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dffmpeg.*"]
namespaces = true

[project.optional-dependencies]
test = [
    "pytest>=9.0.0, <10.0.0",
    "black>=26.1.0, <27.0.0",
    "isort>=7.0.0, <8.0.0",
    "flake8>=7.3.0, <8.0.0",
]
dev = [
    "dffmpeg-worker[test]",
    "ipython>=9.10.0, <10.0.0",
]

[project.scripts]
dffmpeg-worker = "dffmpeg.worker.main:main"
